services:
  spark:
    container_name: spark
    image: bitnami/spark:3.5.0
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - /tmp:/data
    ports:
      - '8100:8080'
    depends_on:
      - hbase-master

  spark-worker-1:
    image: bitnami/spark:3.5.0
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - /tmp:/data

  spark-worker-2:
    image: bitnami/spark:3.5.0
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - /tmp:/data

  zookeeper:
    image: zookeeper:3.4
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - "2181:2181"

  hbase-master:
    image: dajobe/hbase
    container_name: hbase-master
    hostname: hbase-master
    environment:
      - HBASE_CONF_hbase_zookeeper_quorum=zookeeper
    ports:
      - "16000:16000"   # HBase Master port
      - "16010:16010"   # HBase Master UI
    depends_on:
      - zookeeper

  hbase-region:
    image: dajobe/hbase
    container_name: hbase-region
    hostname: hbase-region
    environment:
      - HBASE_CONF_hbase_zookeeper_quorum=zookeeper
    ports:
      - "16020:16020"   # HBase RegionServer port
      - "16030:16030"   # HBase RegionServer UI
    depends_on:
      - hbase-master
      - zookeeper
    command: ["hbase", "regionserver", "start"]

networks:
  default:
    name: develop
    external: true